server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://jj-db.cjoo8ogckqcu.ap-northeast-2.rds.amazonaws.com:3306/jj_db
    username: admin
    password: abc1234!
    driver-class-name: com.mysql.cj.jdbc.Driver


cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET}
    region:
      static: ${REGION}
    stack:
      auto: false

logging:
  level:
    org:
      springframework:
        security: DEBUG

admin:
  email: admin@example.com
  password: admin123

  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
kakao:
  client:
    id: 82cae9ae6aa0eb8f9a9747642144f95e
    secret:
  redirect:
    uri: http://localhost:8080/oauth/kakao/callback
  admin: 7d026139e4ae178402d2fbed022f0cf6


# TODO : 환경변수 처리 하세요!
app:
  token:
    access:
      secret-key: yourSuperSecretKeyAccess1234567890!ThisIsAComplexKey
      expiration: 86400000
    refresh:
      secret-key: yourSuperSecretKeyRefresh1234567890!ThisIsAComplexKey
      expiration: 86400000
  allow-origins: http://localhost:3000
