server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET}
    region:
      static: ${REGION}
    stack:
      auto: false

logging:
  level:
    org:
      springframework:
        security: DEBUG

admin:
  email: admin@example.com
  password: admin123


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
app:
  token:
    access:
      secret-key: ${ACCESSTOKEN_KEY}
      expiration: 86400000
    refresh:
      secret-key: ${REFRESHTOKEN_KEY}
      expiration: 86400000
  allow-origins: http://localhost:3000
